- name: Install elasticsearch
  apt:
    deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ ELASTICSEARCH_VERSION }}.deb"
    state: present
- name: Copy elasticsearch config file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch
- name: Start elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: true
